---
title: "Teaching"
about:
  template: solana
---

## Teaching Associate, Monash University, Australia

### 2025

-   ETC3550/ETC5550 Applied Forecasting [(Handbook Entry)](https://handbook.monash.edu/2025/units/ETC3550)
    -   Conducted tutorial sessions
    
-   ETC2410/ETC5241/BEX2410 Introductory Econometrics [(Handbook Entry)](https://handbook.monash.edu/2025/units/ETC2410?year=2025)
    -   Conducted tutorial sessions
    
-   ETX2250/ETF5922 Data Visualisation and Analytics [(Handbook Entry)](https://handbook.monash.edu/2025/units/ETX2250?year=2025)
    -   Assistant tutor for tutorial sessions

### 2023

-   ETC3400/ETC5340 Principles of Econometrics [(Handbook Entry)](https://handbook.monash.edu/2023/units/ETC3400?year=2023)
    -   Conducted tutorial sessions

### 2022

-   ETC3400/ETC5340 Principles of Econometrics [(Handbook Entry)](https://handbook.monash.edu/2022/units/ETC3400?year=2022)
    -   Conducted tutorial sessions

## Temporary Assistant Lecturer, University of Colombo, Sri Lanka

### Feb 2019 - Feb 2021

-   MS 3009 Operational Research II
    -   Conducted lectures, set exam paper
-   ST 2007 Applications in Statistical Inference
    -   Conducted lectures, set assignments
-   IS 1006 Fundamentals in Statistics
    -   Conducted practical sessions
-   SCS 2211 Laboratory II (Statistical Methods using R)
    -   Conducted lectures
-   ST 1012 Basic Statistical Computing
    -   Conducted practical sessions
-   IS 3053 Data Mining
    -   Teaching Assistant
-   ST 2008 Statistical Methods in Quality Control
    -   Conducted lectures, set exam paper
-   MS 2001 Statistical Quality Control
    -   Conducted lectures, set exam paper